### ISSUE TITLE
Break down ProNET JSON to RPMS like CSVs

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/utility#11]
RPMS has instrument-wise CSVs. But ProNET has a combined JSON. Tashrif will convert `PROTECTED/PronetYA/raw/YA00009/surveys/YA00009.Pronet.json` to PRESCIENT style CSVs. Question is where should we put the broken-down CSVs?

`PROTECTED/PronetYA/processed/YA00009/surveys/YA00009_{instrument}.csv`
or
`PROTECTED/PronetYA/raw/YA00009/surveys/YA00009_{instrument}.csv`

?

---

If we put them in `processed`, to maintain harmony, PRESCIENT's `raw/` CSVs should be copied to `processed/`.

Requesting your opinion overall @kcho

**Comment by kcho** [comment]
This is a great question. We are not doing anything to the raw data, except breaking them up. How about keeping them in the `raw` directory?

Another question that follows this is, how will you group different fields in the `.json` file into `.csv`s? Do you already have an idea how to group them? I saw many fields have prefix that starts with `chr`, eg) `chrmri_`. This could be an option. I'm not sure if there is any other labels from REDCap that we could use to group the fields.

**Comment by tashrifbillah** [comment]
> How about keeping them in the raw directory?

I am fine either way.

---

> how will you group different fields in the .json file into .csvs?

By grouping, do you mean grouping by instruments?

**Comment by tashrifbillah** [comment]
So I did this huge project before https://github.com/AMP-SCZ/gen-fake-data

I am optimistic that that knowledge will be helpful to perform this grouping. I look forward to working on it after two weeks or so.

**Comment by tashrifbillah** [comment]
This task is no longer relevant.

Grace Jacobs is tasked with category-based quality checking of ProNET forms. Her categories are organized by forms. The latter are exported in CSVs by RPMS.

In other words, we started making ProNET-like JSONs from RPMS CSVs.
